### ISSUE TITLE
Idea Table/Research Table - Bug

### ISSUE THREAD

**Issue by SamuelDancing** [TheRActivator/From-the-Ground-Up#16] opened 2017-04-22 19:10 UTC
For some reason when i leave the chunk and reload it while the table is placed inside i can no longer access it and when i break it i don't get the table back, just the contents i was using it in a modpack it's called "Atlantic Survival" but i'm not sure what the problem is for sure.

Please Look into this

**Comment by Astavie** [comment] 2017-04-23 10:14
I did look into it, and it seems Atlantic Survival is using an outdated version of FTGU (version 1.1.2).
This is a duplicate of #13

**Closed as completed by Astavie** 2017-04-23 10:14 UTC
Labels: duplicate, outdated

**Comment by Astavie** [comment] 2017-04-23 10:21
But do tell me if you weren't using 1.1.2
