### ISSUE TITLE
CraftTweaker not supported in 1.11

### ISSUE THREAD

**Issue by TheRealM18** [TheRActivator/From-the-Ground-Up#23] opened 2017-06-09 19:10 UTC
on the wiki you should show an example on how to use it with minetweaker recipemaker since minetweaker3 is no longer a thing.

**Comment by Ksehn** [comment] 2017-06-10 11:19
I don't think MineTweaker RecipeMaker can be used for customizing From the Ground Up. You may have to manually use MineTweaker/CraftTweaker.

**Comment by TheRealM18** [comment] 2017-06-10 13:42
I have tried adding the pages according to what is on the website.  the best i get is that the "mods." but the ftgu call is not registered and I am feeling like i will need to make a mod so that I can make custom pages.  If you could show working test of a .zs file that would be great.

And btw you mod doesn't crash on second time launch into a world.

**Comment by TheRealM18** [comment] 2017-06-10 14:02
btw the code that i think is what you telling us to do is:

https://pastebin.com/MdUnLzjW

if you think there is something wrong can you try and help me debug it.

also if there is a way we could talk that might be useful as well.

**Comment by Ksehn** [comment] 2017-06-10 14:25
Is the following "instruction" working ? :

`mods.ftgu.Page.addPage("my page");`

**Comment by TheRealM18** [comment] 2017-06-10 14:42
im checking right now if you want i can setup a collaborator page so that i can update live.  I get 

[11:30:11] [Client thread/INFO]: [CHAT] ERROR: Error executing test.zs: Bad type on operand stack\nException Details:\n  Location:\n    Test.__script__()V @26: invokestatic\n  Reason:\n    Type 'stanhebben/zenscript/value/IAny' (current frame, stack[4]) is not assignable to 'java/lang/String'\n  Current Frame:\n    bci: @26\n    flags: { }\n    locals: { top, 'java/lang/String' }\n    stack: { null, '[Lstanhebben/zenscript/value/IAny;', '[Lstanhebben/zenscript/value/IAny;', integer, 'stanhebben/zenscript/value/IAny' }\n  Bytecode:\n    0x0000000: 120b 4c01 120c bd00 0e59 120f 120b 59c7\n    0x0000010: 0008 5701 a700 06b8 0015 b800 1b53 b900\n    0x0000020: 1f02 0057 b1                           \n  Stackmap Table:\n    full_frame(@23,{Top,Object[#33]},{Null,Object[#35],Object[#35],Integer,Object[#33]})\n    full_frame(@26,{Top,Object[#33]},{Null,Object[#35],Object[#35],Integer,Object[#14]})\n

**Comment by Ksehn** [comment] 2017-06-10 14:49
As you want, but I'm not a Mine/CraftTweaker expert ^^'.

**Comment by TheRealM18** [comment] 2017-06-10 14:50
if you would like to help me debug this problem or see it live tested i can show you/join you on discord and/or work with it in a collabedit.com page like http://collabedit.com/kxnq9 and discord would be https://discord.gg/GFu2dt

**Comment by Astavie** [comment] 2017-06-10 15:02
I'm not sure what you mean with "MineTweaker 3 is no longer a thing". Sure, the original author stopped developing it, but CraftTweaker is a continuation of MineTweaker and that is what I use.

I have never heard of MineTweaker RecipeMaker, so it will most likely not be supported.

**Comment by Astavie** [comment] 2017-06-10 15:05
Uhm... CraftTweaker support might be broken in 1.11 due to mod id changes. I'll look into this.
Edit: yes, it is indeed broken in 1.11

**Comment by Ksehn** [comment] 2017-06-10 15:11
I can confirm this. Good luck to fix this @TheRActivator.

**Forge :** 13.20.0.2315
**From the Ground Up :** 1.11.2-b1.1.4
**CraftTweaker :** 1.11.2-3.0.25


CraftTweaker logs : https://pastebin.com/raw/YCLGpfwY
CraftTweaker script : https://pastebin.com/raw/KwKd9RuC

**Comment by Astavie** [comment] 2017-06-12 20:09
fixed in 1.1.5. see curseforge

**Comment by KsenMih** [comment] 2017-06-12 20:10
Yeay !

**Closed as completed by Astavie** 2017-06-12 20:09 UTC
Labels: bug, compat
